apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: application-agent-runtime-data
  namespace: ai-agent-fwk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
