"""Narrow protocols used by the LangGraph Runtime Service."""
from __future__ import annotations
from typing import Any, Mapping, Protocol
from .models import AgentVersionReference

class AgentVersionRepository(Protocol):
    def get_active(self, agent_id: str) -> AgentVersionReference: ...
    def get_version(self, agent_id: str, version: str) -> AgentVersionReference: ...

class AgentCompiler(Protocol):
    def compile(self, *, definition: Any, dependencies: Any, checkpointer: Any) -> Any: ...

class ConversationMetadataStore(Protocol):
    def create(self, **values: Any) -> Any: ...
    def get(self, conversation_id: str) -> Any: ...
    def update(self, **values: Any) -> Any: ...

class DependencyFactory(Protocol):
    def create(self, definition: Any) -> Any: ...

class CompiledAgentProtocol(Protocol):
    def invoke(self, *, conversation_id: str, state: Mapping[str, Any]) -> Any: ...
    def resume(self, *, conversation_id: str, command: Any) -> Any: ...
    def get_state(self, *, conversation_id: str) -> Any: ...
